name: backend

on:
  push:
    paths:
    - ".github/workflows/backend.yml"
    - "CMakeLists.txt"
    - "src/*"
    - "scripts/*"
  pull_request:
    paths:
    - ".github/workflows/backend.yml"
    - "CMakeLists.txt"
    - "src/*"
    - "scripts/*"
  workflow_call:

jobs:
  cross:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        target: [i686, x86_64, arm, armhf, aarch64, mips, mipsel, mips64, mips64el, s390x]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake build-essential cmake curl file libtool
      - name: Cross build (${{ matrix.target }})
        env:
          BUILD_TARGET: ${{ matrix.target }}
        run: ./scripts/cross-build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: ttyd.${{ matrix.target }}
          path: build/ttyd*

  macos:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
            arch: arm64
          - os: macos-13
            arch: x86_64
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          brew install cmake json-c libwebsockets libuv
      - name: Build for macOS (${{ matrix.arch }})
        run: |
          mkdir -p build && cd build
          cmake ..
          make
          file ttyd
      - uses: actions/upload-artifact@v4
        with:
          name: ttyd.macos-${{ matrix.arch }}
          path: build/ttyd

